version: '3'
services:
  hello1:
    build: .
    image: hello:local
    environment:
      ES_HOST: elasticsearch:9200
    volumes:
      - ./app.py:/app/app.py
  hello2:
    image: hello:local
    environment:
      ES_HOST: elasticsearch:9200
    volumes:
      - ./app.py:/app/app.py
  hello3:
    image: hello:local
    environment:
      ES_HOST: elasticsearch:9200
    volumes:
      - ./app.py:/app/app.py
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
