version: '3.7'
services:
  toy-flask:
    build: .
    image: toy-flask:local
    environment:
      ES_HOST: elasticsearch:9200
    volumes:
      - ./app.py:/app/app.py
  toy-flask-2:
    image: toy-flask:local
    environment:
      ES_HOST: elasticsearch:9200
    volumes:
      - ./app.py:/app/app.py
  toy-flask-3:
    image: toy-flask:local
    environment:
      ES_HOST: elasticsearch:9200
    volumes:
      - ./app.py:/app/app.py
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  toy-flask-test:
    build:
      context: .
      target: test-image
    image: toy-flask:local-test
    environment:
      ES_HOST: elasticsearch:9200
      TOY_FLASK_HOST: nginx:80
    # TODO: see if we can make integration tests run as part of docker-compose up using depends_on and healthchecks
    volumes:
      - ./tests:/app/tests
    command: echo "Run me separately!"
