version: '3.7'
services:
  toy-flask:
    build: .
    image: toy-flask:local
    environment:
      ES_HOST: elasticsearch:9200
    volumes:
      - ./app.py:/app/app.py
  toy-flask-2:
    image: toy-flask:local
    environment:
      ES_HOST: elasticsearch:9200
    volumes:
      - ./app.py:/app/app.py
  toy-flask-3:
    image: toy-flask:local
    environment:
      ES_HOST: elasticsearch:9200
    volumes:
      - ./app.py:/app/app.py
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  toy-flask-test:
    build:
      context: .
      target: test-image
    image: toy-flask:local-test
    environment:
      ES_HOST: elasticsearch:9200
      TOY_FLASK_HOST: nginx:80
    volumes:
      - ./tests:/app/tests
    # Run integration tests
    command: pytest tests/integration/

  #   # TODO: decide if it'd be better to roll integration test into unit test image
  #   # Pros:
  #   # - Can leverage cache of app image for build
  #   # - One less Dockerfile to manage
  #   # Cons:
  #   # - Couples integration tests with app code -- integration tests shouldn't
  #   #   need any app code to run
  #   toy-flask-integration-test:
  #     build:
  #       context: .
  #       dockerfile: tests/integration/Dockerfile-integration_test
  #     image: toy-flask-integration-test:local
  #     environment:
  #       ES_HOST: elasticsearch:9200
  #       TOY_FLASK_HOST: nginx:80
  #     volumes:
  #       - ./tests:/app/tests/integration/
  #     command: pytest tests/integration/
