version: '3'
services:
  toy-flask-1:
    build: .
    image: toy-flask:local
    environment:
      ES_HOST: elasticsearch:9200
  toy-flask-2:
    image: toy-flask:local
    environment:
      ES_HOST: elasticsearch:9200
  toy-flask-3:
    image: toy-flask:local
    environment:
      ES_HOST: elasticsearch:9200
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
